name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tylerandersonmendio/juice-box:${{ github.event.repository.name }}:${{ github.run_id }}

    - name: Authenticating and Pushing Docker Image
      run: |
            echo "Authentication..."
            docker login --username ${{ secrets.MEND_EMAIL }} --password ${{ secrets.DOCKER_PW }}

            echo "Pushing Docker"
            docker push tylerandersonmendio/juice-box:${{ github.event.repository.name }}:${{ github.run_id }}

    - name: Deleting Local Docker Image
      run: docker image remove tylerandersonmendio/juice-box:${{ github.event.repository.name }}:${{ github.run_id }}
      

    - name: Downloading the Scanners
      run: |
        echo "Downloading the CLI"
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend

    - name: Validating the CLI
      run: |
        echo "Verifying the CLI"
        mend version

    - name: "Running the CLI"
      run: |
            mend image tylerandersonmendio/juice-box:${{ github.event.repository.name }}:${{ github.run_id }} --non-interactive --local-pull --scope "Tyler-Sandbox//${{ github.event.repository.name }}//NonLocalDocker"
      env:
        MEND_USER_KEY: ${{ secrets.WS_USERKEY }}
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_URL: ${{ secrets.MEND_URL }}
        MEND_LOG_LEVEL: "DEBUG"
    
