name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:${{ github.run_id }}

    - name: Downloading the Scanners
      run: |
        echo "Downloading the CLI"
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend

    - name: Validating the CLI
      run: |
        echo "Verifying the CLI"
        mend version

    - name: "Running the CLI"
      run: |
            mend image ${{ github.event.repository.name }}:${{ github.run_id }}> --non-interactive --local_pull --scope "Tyler_Github_Scans//${{ github.event.repository.name }}//FromDocker"
      env:
        MEND_USER_KEY: ${{ secrets.WS_USERKEY }}
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_URL: ${{ secrets.MEND_URL }}
        MEND_LOG_LEVEL: "DEBUG"
    
