name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tylerandersonmendio/${{ github.event.repository.name }}:${{ github.run_id }}

    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      uses: docker/login-action@v3.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: ${{ secrets.DOCKER_URL }}
        # Username used to log against the Docker registry
        username: ${{ secrets.MEND_EMAIL }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PW }}
        # # Specifies whether the given registry is ECR (auto, true or false)
        # ecr: # optional, default is auto
        # # Log out from the Docker registry at the end of a job
        # logout: # optional, default is true
          

    # - name: Pushing Docker Image
    #   run: |
    #         echo "Pushing Docker"
    #         docker push tylerandersonmendio/${{ github.event.repository.name }}:${{ github.run_id }}

    # - name: Deleting Local Docker Image
    #   run: docker image remove tylerandersonmendio/${{ github.event.repository.name }}:${{ github.run_id }}
      

    - name: Downloading the Scanners
      run: |
        echo "Downloading the CLI"
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend

    - name: Validating the CLI
      run: |
        echo "Verifying the CLI"
        mend version

    - name: "Running the CLI"
      run: |
            mend dep . --non-interactive --local-pull --scope "Tyler-Sandbox//${{ github.event.repository.name }}//NonLocalDocker-${{ github.run_id }}"
      env:
        MEND_USER_KEY: ${{ secrets.WS_USERKEY }}
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_URL: ${{ secrets.MEND_URL }}
        MEND_LOG_LEVEL: "DEBUG"
        MEND_SCA_REACHABILITY: "true"
    
